### ISSUE TITLE
sec:authorize-url expressions always true

### ISSUE THREAD

**Issue by spacejens** [thymeleaf/thymeleaf-extras-springsecurity#18]
I am attempting to use sec:authorize-url in Thymeleaf pages, but it seems to always evaluate as true (i.e. the tags always show in the browser). This is confusing, as the URL (backed by a controller with a @PreAuthorize annotation using hasPermission) is not accessible to all users.

My code is here on GitHub, in my GaGrOr project. I made a commit on a separate branch (thymeleaf-springsecurity) trying several variants of security expressions to present a link if the URL (backed by AccountController.java) is allowed by the user:
https://github.com/spacejens/GaGrOr/commit/cf20f41a82f34a09fd31e95f95a9fd00ddac206b

Apologies for the possible duplication of https://github.com/thymeleaf/thymeleaf-extras-springsecurity3/issues/17 but since they are two different but possibly related problems I created two issues.

**Comment by spacejens** [comment]
It is worth noting that the sec:authorize="hasRole... works as expected, i.e. only users with the specified role see the links. So I am confused as to why the other sec:... stuff is not working. And yes, I am aware that I am quite likely doing something wrong here...

**Comment by danielfernandez** [comment]
From your code, two of your `sec:authorize-url` examples use Thymeleaf Standard Expressions (`${...}`) and (`@{...}`), which is not allowed. Values of `sec:authorize-url` must match what is allowed by the URL validation method established by Spring Security itself (e.g. in its JSP taglib), which means that it expects an URL, not a _foreign_ (Thymeleaf's) expression generating an URL.

In order to be able to use URLs generated with `@{...}` expressions (which are Thymeleaf's), you'd need to use a `th:if` and an expression for it calling the `#authorization.url(...)` method. `th:if`, being a _Thymeleaf proper_ attribute (and not a mere delegation to Spring Security) will allow you to use pre-processing just fine, so that you can generate your URL using link expressions.

**Comment by danielfernandez** [comment]
I've just created #40 in order to allow the direct use of pre-processing in `sec:*` attributes. Therefore I'm closing this for now, as it seems all needs expressed here should be covered by #40. Please don't hesitate reopening if you think there is anything else that needs clarification.
