### ISSUE TITLE
Spring Security 4 support.

### ISSUE THREAD

**Issue by wienczny** [thymeleaf/thymeleaf-extras-springsecurity#21]
WebSecurityExpressionHandler has been deprecated in Spring Security 3.1 removed in Spring Security 4. It has been replaced by SecurityExpressionHandler<FilterInvocation> like you can see in http://docs.spring.io/autorepo/docs/spring-security/3.2.4.RELEASE/apidocs/index.html?org/springframework/security/web/access/expression/WebSecurityExpressionHandler.html
Please consider dropping support for Spring Security 3.0 and move to SecurityExpressionHandler<FilterInvocation>

**Comment by willdavidwarren** [comment]
Wouldn't it make more sense to only support `SecurityExpressionHandler` in a `thymeleaf-extras-springsecurity4` library - if one ever came about?

**Comment by wienczny** [comment]
I've forked springsecurity3 and refactored it into https://github.com/wienczny/thymeleaf-extras-springsecurity3/tree/springsecurity4

**Comment by cm-rudolph** [comment]
I've forked the integration, too before I saw that there is already a fork... My solution with a minimal amount of changes can be seen here:
https://github.com/cm-rudolph/thymeleaf-extras-springsecurity4
It might be good to put spring security 4 support into a separate branch and not a complete new project, because the changes are so minimal. So it should be possible to rebase it when development goes on.

**Comment by cm-rudolph** [comment]
Another approach could be to add spring security 4 support using a delegate to support `getExpressionParser()` and `createEvaluationContext()` in a version independent way.

**Comment by wienczny** [comment]
@cm-rudolph I'm not sure I understand what you propose. How would that solve the problem that you can't have both SpringSecurity versions as dependency when building? Either the SS3 or SS4 implementation would break, unless you used the SS4 SecurityExpressionHandler which on the other side would not work with old SS3. This was my first proposal and rejected.
The only way you could implement a delegate is by splitting the package in 3 parts: Common with interfaces and the implementations in SS3 and SS4.

**Comment by cm-rudolph** [comment]
The only problem is with building the thymeleaf extension, because spring 3 and spring 4 can't be configured as (provided) dependencies at the same time.
I think the simplest solution would be to copy the `WebSecurityExpressionHandler` interface into a separate package that is given as (provided) dependency just for the purpose of building `thymeleaf-extras-springsecurity`.
Within the extension the spring security detection would be done via reflection, as it is already implemented for the spring framework detection.
The delegate would be an interface exactly as `WebSecurityExpressionHandler`, but in a different package - a package beginning with `org.thymeleaf`.

**Comment by cm-rudolph** [comment]
I implemented what I described but instead of creating a separate artifact containing the copied `WebSecurityExpressionHandler` interface, I excluded the interface from packaging in the generated artifact (source, javadocs and jar).
This can be seen in d0212ce5f1d6bb99051a1eff296e1aeb2f00833d . In e84149d2c21287f2f0a3b22591a86686d122f11e I implemented the delegating utility classes.

**Comment by danielfernandez** [comment]
Unfortunately we cannot / should not remove support for Spring Security 3.0 in Thymeleaf 2.1, so simply switching from `WebSecurityExpressionHandler` to the _new_ (as of Spring Security 3.1) `SecurityExpressionHandler` interface would not be a feasible option for us.

Besides, supporting Spring Security 4 with an integration package called `thymeleaf-extras-springsecurity3` does not look completely OK ;)

So for us the most correct and most future-proof solution will be to rename this repository to `thymeleaf-extras-springsecurity` and divide it into two different (though very similar --- almost equal) projects called `thymeleaf-extras-springsecurity3` and `thymeleaf-extras-springsecurity4`. This is exactly what was done to the `thymeleaf-spring3` repository when it became `thymeleaf-spring` in order to create the `thymeleaf-spring4` project, so it will be a solution quite consistent with the rest of the project's organization.

So `thymeleaf-extras-springsecurity3` will remain using the (deprecated) interface and `thymeleaf-extras-springsecurity4` will use the new one.

Needed changes:
- Rename the current `thymeleaf-extras-springsecurity3` repository to `thymeleaf-extras-springsecurity`.
- Move all existing code to a `thymeleaf-extras-springsecurity3` folder inside the renamed repository.
- Create an almost-exact copy (for now) of the code in `thymeleaf-extras-springsecurity3` into a new `thymeleaf-extras-springsecurity4` folder, modifying dependencies for using Spring Security 4 (the RC for now) and modifying the code in the `AuthUtils` class to use the new interface.
- Generalize all kind of existing documentation for the `thymeleaf-extras-springsecurity3` module, so that both Spring Security 3 and Spring Security 4 support are covered. Nowadays, this “all kind of existing documentation” basically means the README.
- (Afterwards) updating @jmiguelsamper 's article and example application on Spring Security integration.

**Comment by danielfernandez** [comment]
I've just uploaded a first snapshot of the `thymeleaf-extras-springsecurity4` module, version `2.1.2-SNAPSHOT`. You can include it in your apps for testing as:

``` xml
  <repositories>
    <repository>
      <id>sonatype-nexus-snapshots</id>
      <name>Sonatype Nexus Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
    ...
  </repositories>
  ...
  <dependencies>
    ...
    <dependency>
      <groupId>org.thymeleaf.extras</groupId>
      <artifactId>thymeleaf-extras-springsecurity4</artifactId>
      <version>2.1.2-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    ...
  </dependencies>
```

**Comment by danielfernandez** [comment]
I've also created a `springsecurity4` branch at the thymeleafexamples-springsecurity example application exemplifying the use of this new module and Spring Security 4.0. See https://github.com/thymeleaf/thymeleafexamples-springsecurity/commit/3d1c16865cef94833e8721a99b93cfb2cbb7ba19

**Comment by cm-rudolph** [comment]
@danielfernandez I commented on your commit cb5680253e6f9a31b7bbd6ff656c576133793908 because your adjustments are incomplete concerning type safety.

**Comment by chrylis** [comment]
I see that the SEC 4.0 module is here, but it's not available in Central yet. I'm using features that require 4.0, and of course the `WebSecurityExpressionHandler` is no longer available. Is there any word on artifact availability?

**Comment by danielfernandez** [comment]
@chrylis given Spring Security 4.0 is not GA yet, we don't have a stable release for it. What we have is a working snapshot (see above). We will release a first stable release as soon as Spring Security 4.0 is published.

**Comment by chrylis** [comment]
For some reason, Maven wasn't resolving OSSRH snapshots. It's working just fine for me now.

**Comment by odrotbohm** [comment]
Spring Security 4.0 just went GA. Maybe time to bundle up a release? ;)

**Comment by cm-rudolph** [comment]
And what about my pull request #24?

**Comment by ultraq** [comment]
> Spring Security 4.0 just went GA. Maybe time to bundle up a release? ;)

:stuck_out_tongue:

**Comment by danielfernandez** [comment]
Definitely. Will publish it ASAP

**Comment by odrotbohm** [comment]
:+1:

**Comment by danielfernandez** [comment]
`thymeleaf-extras-springsecurity4` version `2.1.2.RELEASE` just published. Please allow some time for the Maven repos to sync.

**Comment by odrotbohm** [comment]
Thanks Daniel, that was quick! :)

**Comment by rcuadrado** [comment]
Is that working?, because when I use (thymeleaf-extras-springsecurity4)  (2.1.2.RELEASE), and use the following sentence
```javascript
<div id="navbar" class="navbar-collapse collapse" th:if="${#authorization.expression('isAuthenticated()')}">
```
an exception is thrown: 
```
java.lang.IllegalArgumentException: Authentication object cannot be null
	org.springframework.security.access.expression.SecurityExpressionRoot.<init>(SecurityExpressionRoot.java:46)
	org.springframework.security.web.access.expression.WebSecurityExpressionRoot.<init>(WebSecurityExpressionRoot.java:21)
	org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler.createSecurityExpressionRoot(DefaultWebSecurityExpressionHandler.java:27)
	org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler.createSecurityExpressionRoot(DefaultWebSecurityExpressionHandler.java:17)
	org.springframework.security.access.expression.AbstractSecurityExpressionHandler.createEvaluationContext(AbstractSecurityExpressionHandler.java:51)
	org.thymeleaf.extras.springsecurity4.auth.AuthUtils.authorizeUsingAccessExpression(AuthUtils.java:196)
	org.thymeleaf.extras.springsecurity4.auth.Authorization.expression(Authorization.java:103)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
```
spring: 4.1.6.RELEASE
spring-security: 4.0.0.RELEASE
thymeleaf: 2.1.4.RELEASE

**Comment by danielfernandez** [comment]
@rcuadrado your expression works for me using exactly the same versions as you... maybe some other problem in your Spring Security configuration?

**Comment by danielfernandez** [comment]
@rcuadrado by the way, you can set your log for `org.thymeleaf.extras.springsecurity4.auth.AuthUtils` to `TRACE` and this should show you the different reasons that can happen for your Authentication object to be null...
