### ISSUE TITLE
sec:authorize is not working for list.

### ISSUE THREAD

**Issue by DavidGarciaHerrera** [thymeleaf/thymeleaf-extras-springsecurity#25]
When you try to load a list of roles from a xml you dont have access to this if you used:

```
<div th:if="${#authorization.expression('hasAnyRole(''${menuItem.getRoles()}'')')}">
```

you need to modiffy the access and put like this:

```
<div th:if="${#authorization.expression('hasAnyRole(''__${menuItem.getRoles()}__'')')}">
```

for more information of the code that I'm using you can check:

http://forum.thymeleaf.org/sec-authorization-problems-to-load-a-list-td4028823.html
or 
https://stackoverflow.com/questions/29076889/problems-with-secautorize-thymeleaf

**Comment by danielfernandez** [comment]
Spring Security's authorization expressions are executed on Spring Security's own evaluation context (and they should be in order to be consistent with how Spring Security works in other environments). 

However, Thymeleaf offers the possibility to access model attributes (context variables) in these authorization expressions by means of the `#vars` expression object. See https://github.com/thymeleaf/thymeleaf-extras-springsecurity#using-the-attributes
