### ISSUE TITLE
sec:authorize with hasPermission don't process local variables

### ISSUE THREAD

**Issue by klebermo** [thymeleaf/thymeleaf-extras-springsecurity#30]
I am trying to use this:

``` java
hasPermission(#user, 'listagem_${item.simpleName}')
```

with sec:authorize in a spring /  thymeleaf code, but when I deploy and run the application this code isn't processed, and it's being display as is.

I try envolve the expression with |...|, but in this case I get the error:

``` java
org.springframework.expression.spel.SpelParseException: EL1069E:(pos 0): missing expected character '|'
```

**Comment by danielfernandez** [comment]
Spring Security's authorization expressions are executed on Spring Security's own evaluation context (and they should be in order to be consistent with how Spring Security works in other environments). 

However, Thymeleaf offers the possibility to access model attributes (context variables) in these authorization expressions by means of the `#vars` expression object. See https://github.com/thymeleaf/thymeleaf-extras-springsecurity#using-the-attributes
