### ISSUE TITLE
include Spring MVC model in evaluation context

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf-extras-springsecurity#31]
I'm trying to write an `authorize` expression using model variables, but it seems they aren't being added to the `Arguments` for the evaluator, although the request path variables are. It seems to me that the model ought to be available here.

**Comment by danielfernandez** [comment]
Spring Security's authorization expressions are executed on Spring Security's own evaluation context (and they should be in order to be consistent with how Spring Security works in other environments). 

However, Thymeleaf offers the possibility to access model attributes (context variables) in these authorization expressions by means of the `#vars` expression object. See https://github.com/thymeleaf/thymeleaf-extras-springsecurity#using-the-attributes
