### ISSUE TITLE
sec-authorized-url stop working with spring-cloud-aws-autoconfigure

### ISSUE THREAD

**Issue by setterlee** [thymeleaf/thymeleaf-extras-springsecurity#35]
I have an spring-boot project working with thymeleaf and all my menu options are listed with the tag "sec:authorize-url=/example".

everything was fine till i implemented an S3 (aws) file uploading event in my code. 

if i include the library "spring-cloud-aws-autoconfigure" in the project, the security tag stop work.

**Comment by danielfernandez** [comment]
There should be no reason (from the Thymeleaf standpoint) for a new Spring Cloud module to modify the way your URL authorization expressions are executed.

However, just in case: Versions `2.1.3.RELEASE` (for Thymeleaf 2.1) and `3.0.1.RELEASE` (for Thymeleaf 3.0) of the Spring Security integration module have just been published, and they include an improvement no the way the `PrivilegeEvaluator` used for evaluating URL authorization expressions is obtained, which makes Thymeleaf now match exactly what is done in Spring Security since version 4.1.0.

If this doesn't work, I'm afraid the error is most surely somewhere else in your Spring Security setup, as Thymeleaf will be just doing the same as Spring Security's own JSP tag library does...
