### ISSUE TITLE
Spring 5 support

### ISSUE THREAD

**Issue by Ansraer** [thymeleaf/thymeleaf-extras-springsecurity#47]
Is there any reason why there is no spring 5 version yet? I mean, the code is already there. All that needs to be done is to rename all packages to org.thymeleaf.extras.springsecurity5 so that the class loader finds the correct class.

If anyone else has encountered this problem and wants to have a fix until there is a new version in the maven repo: import the thymeleaf-extras-springsecurity4 folder as a maven project into your ide, rename the packages so that they match with the thymleaf/spring version you are using and change the artifact and name in the pom file. Just build it with maven now and import the jar into your project

**Comment by danielfernandez** [comment]
Hello @Jacky2611… what do you mean? There is no Spring Security version 5 yet, not even a milestone. What there are is several milestones of **Spring Framework** (latest: `5.0.0.M5`), which is a separate project from Spring Security, and that is already been covered by our `thymeleaf-spring5` package (also in *milestone* stage).

Anyway, you can use the `thymeleaf-extras-springsecurity4` package with the `thymeleaf-spring5` one... or are you finding any problem in doing so?

**Comment by Ansraer** [comment]
I am currently running a maven project with spring boot 2.0.0.BUILD-SNAPSHOT and a spring-boot-starter-security dependency. This does give me a 5.0.0BUILD-SNAPSHOT Spring Security jar.

My problem is that SpringVersionSpecificUtils uses getPackage().getName() and then throws an ClassNotFound Exception when it tries to use this path to find a class from thymeleaf-spring5 since the packagename is wrong. I fixed it by simply renaming all the packages to _org.thymeleaf.extras.springsecurity5_


EDIT: It could be that the version 5 can only be found in the snapshot repo. Not sure right now.
`    <repository>
        <id>spring-snapshots</id>
        <name>Spring Snapshots</name>
        <url>https://repo.spring.io/libs-snapshot</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>`

**Comment by danielfernandez** [comment]
Oh, I see. It's not really a package naming issue, but a lack of support.

I'm afraid your issue is due to the fact that Spring Boot  `2.0.0.BUILD-SNAPSHOT` is currently using as default version of `thymeleaf-extras-springsecurity4` version `3.0.1.RELEASE`, which is not prepared to work with Spring 5. If you update your `thymeleaf-extras-springsecurity4` dependency to `3.0.2.RELEASE` it should work for you.

As for creating a module for Spring Security 5: There are `5.0.0.BUILD-SNAPSHOT` snapshots, but as I said there isn't even a first milestone yet. Thymeleaf integration releases should depend on (at least) milestone versions (for example, `thymeleaf-spring5` currently depends on Spring Framework `5.0.0.M5`), but obviously not on snapshots which API could change in a matter of days. So there is no real point in having a `thymeleaf-extras-springsecurity5` for now. Using the one for Spring Security 4 you should be fine.

**Comment by danielfernandez** [comment]
This is the Spring Boot ticket for this version update: spring-projects/spring-boot#8530

**Comment by cbartolome** [comment]
Looks like `spring-boot-starter-thymeleaf` version `2.0.0.RELEASE` is freshly out, so this is relevant again. Should I re-file this issue? Or maybe try to whip up a pull request, assuming it's really as easy as renaming the packages?

**Comment by danielfernandez** [comment]
@cbartolome  There already is a `thymeleaf-spring5` module (since quite a long ago, in fact), including support for Spring WebFlux. If you mean support for **Spring Security 5**, that is already underway, but it is definitely not as easy as *renaming the packages* as it has to include support for the reactive parts of Spring Security 5 too (for WebFlux). And that is giving quite a lot of extra work.

However, using `thymeleaf-extras-springsecurity4` with Spring Boot 2.0.0 and `thymeleaf-spring5` is perfectly fine (in fact, that's the combination used by Spring Boot 2.0.0).

**Comment by russellhoff** [comment]
@danielfernandez so, am I able to use `thymeleaf-extras-springsecurity4` until the release of `thymeleaf-extras-springsecurity5` without any hassle or difficulty? Thank you so much!

PS: is there any roadmap to see the development of `thymeleaf-extras-springsecurity5`?

**Comment by danielfernandez** [comment]
@russellhoff that's correct. And `thymeleaf-extras-springsecurity5` is almost ready, but a requirement at the reactive side needs a change at the `thymeleaf-spring5` module that will come in version `3.0.10.RELEASE` of the core, which should be published in a couple of weeks.
