### ISSUE TITLE
Permissions resolution not working with authorize-url and multiple http realms

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf-extras-springsecurity#5]
Permissions resolution not working with authorize-url and multiple http realms because only first `org.springframework.security.web.access.WebInvocationPrivilegeEvaluator` in `AuthUtils` is used and others are ommited (`AuthUtils` line 289).

**Comment by danielfernandez** [comment]
This in fact mimics the behaviour of the official Spring Security "authorize" tag (see http://grepcode.com/file/repo1.maven.org/maven2/org.springframework.security/spring-security-taglibs/3.1.1.RELEASE/org/springframework/security/taglibs/authz/AbstractAuthorizeTag.java#340 ), which only uses the first `WebInvocationPrivilegeEvaluator` instance.

And the same happens with the `ExpressionHandler` instance, also mimicing the original JSP tag's behaviour.

If support for more than one evaluator of each of these two kinds was added in thymeleaf, how do you think it should work?

**Comment by kreuzman** [comment]
Hi I realize this also and it is little disappointment with official Spring Security tag library. So I think the best way is to wait for next version of Spring Security and see how they change it (I'll also report it to Spring Security team). 

But if you want to change this behavior (I'm not sure if it's good to make it) in Thymeleaf I've made simple hack and returning array of  `WebSecurityExpressionHandler` and iterate over it. I can commit/send you source code if you want to.

**Comment by chkluwe** [comment]
Hello,

I just ran into the same problem. The corresponding lines in the code of the Spring Security taglib according to Github are from 2010 - they predate the 3.1 Release. So I guess they simply didn't update the taglib for multiple http realms.

I agree with Michal on how this should work: since with multiple http realms each interceptor is still configured for paths relative to the context-root, a check with all available `WebInvocationPrivilegeEvaluator` beans is the way to go (see my fork).

For the `WebSecurityExpressionHandler` I'd too wait what the Spring Security team does. This interface is deprecated in their current master branch.

Regards,
Chris

**Comment by danielfernandez** [comment]
Please note this should be fixed now thanks to #36, #37, #38 and #39
