### ISSUE TITLE
sec:authorize-url attribute does not evaluate expression

### ISSUE THREAD

**Issue by gduchesneau** [thymeleaf/thymeleaf-extras-springsecurity#7]
sec:authorize-url attribute does not evaluate @{...} or ${...} expressions.  It would be really useful if it would.

For instance, it is not possible to build a dynamic nav bar like this:

```
<ul id="my-navbar">
    <!-- let's say we have a "links" object that is a collection of href with text label pairs -->
    <li th:each="link : ${links}" sec:authorize-url="@{${link.href}}">
        <a th:href="@{${links.href}}" th:text="${link.text}"></a>
    </li>
</ul>
```

The only thing that seems to be missing to support that is to change the first few lines in AuthorizeUrlAttrProcessor.isVisible() with : 

```
    String attributeValue = element.getAttributeValue(attributeName);

    if (attributeValue == null || StringUtils.isEmpty(attributeValue).booleanValue())
    {
        return false;
    }

    // Resolve expression
    attributeValue = (String) StandardExpressionProcessor.processExpression(arguments, attributeValue);

    ...
```

**Comment by gkonst** [comment]
I have the same problem!

**Comment by danielfernandez** [comment]
Actually, `sec:authorize-url` and the other `sec:*` attributes use a different expression language than thymeleaf''s, which is Spring Security's own expression language. This is done so in order to allow an easier transition from Spring Security's JSP tags to thymeleaf's dialect.

In order to allow the integration of Spring Security features into Thymeleaf standard expressions, this library includes the `#authentication` and `#authorization` utility objects, which can be used like:

``` html
<div th:if="${#authorization.expression('hasRole(''ROLE_ADMIN'')')}">
        This will only be displayed if authenticated user has role ROLE_ADMIN.
</div>
```

See https://github.com/thymeleaf/thymeleaf-extras-springsecurity3#using-the-expression-utility-objects

I'm therefore closing this issue, considering it solved by the use of these objects. If this doesn't suit your needs, feel free to reopen it.
